/**
 * Created by 荼蘼 on 2017-08-23.
 */
module.exports = function loadAllItems(){
    return [
        {
            number:0,
            barcode:'||:::'
         },
        {
            number:1,
            barcode:':::||'
        },
        {
            number:2,
            barcode:'::|:|'
         },
        {
            number:3,
            barcode:'::||:'
        },
        {
            number:4,
            barcode:':|::|'
        },
        {
            number:5,
            barcode:':|:|:'
        },
        {
            number:6,
            barcode:':||::'
        },
        {
            number:7,
            barcode:'|:::|'
        },
        {
            number:8,
            barcode:'|::|:'
        },
        {
            number:9,
            barcode:'|:|::'
        }
    ];
}